server:
  port: 9527

spring:
  application:
    name: MicroServiceCloud-Zuul-Gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: Gateway9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /Provider/**
  ignored-services: "*"
  prefix: /simon

info:
  app.name: Simon-MicroServiceCloud
  company.name: www.simon.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
